version: '3.9'


networks:
  webnet:
    driver: bridge


volumes:
  nginx_logs:


services:
  angular_nginx:
    build: .
    image: isseu123/devoir-angular:latest
    container_name: angular_nginx
    ports:
      - '8080:80'
    networks:
      - webnet
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    restart: unless-stopped